### ISSUE TITLE
Adjustment instead of Block request

### ISSUE THREAD

**Issue by zerafox** [antiAD/AntiAd#35]
I love that this plugin does exactly what it is supposed to do, it will do wonders on my server.
I do however request that a feature be added to instead of block messages with a spam trigger, it corrects them?

IE: HELLO! -> Hello!

**Comment by KasperFranz** [comment]
It is added so it's comming in 2.3.0 :) 

Should it still warn the player or not?

**Comment by XxCoolGamesxX** [comment]
Be good warn the player to not spam or etc.

**Comment by KasperFranz** [comment]
They currently get the warning as if it was removed 

Sent using Boxer

Den 14/02/2016 11.08 PM skrev Charles <notifications@github.com>:

Be good warn the player to not spam or etc.

**Comment by XxCoolGamesxX** [comment]
ah ok, my bad.

**Comment by KasperFranz** [comment]
So was more if we shouldn't warm them since it is "fixed"
