### ISSUE TITLE
some errors or cant understand things in the plugin (remake accident first one)

### ISSUE THREAD

**Issue by LegitCake100** [antiAD/AntiAd#44]
Dear developers,
 Please help me if you can because the plugin in my server is acting so weird in the caps detection setting, if i set the caps detection to false it still detects caps. Another thing Developers if the caps procent or percent is 100 and players typed more than 3 words of caps does it includes spamming? how if i put 50 and below its still spamming cause its kinda weird for me, another thing is that if player still keeps spamming or doing things that is cause the plugin to give them warning it goes to a crash but the plugin doesnt give a WARN things or errors it just give us Java thing msg when kicked but nothing happening in console and does this plugin have the duplicate msg thing? and like if player caps they will be just edited to small letters like the right caps and the right things to be in cap like if players do ABC.ABC it will be converted to Abc.Abc or HEY!!!!!! it will be just Hey!. Please Developers do help me if you can TY verymuch
   P.S How to set signature in bukkit :D hahaha just asking :P

**Comment by KasperFranz** [comment]
Should be fixed in the latest release, which shoul come live tomorrow.

If it is still present please make a new ticket :)
