### ISSUE TITLE
Star alias to the advertisement whitelist

### ISSUE THREAD

**Issue by XxCoolGamesxX** [antiAD/AntiAd#49]
Hello,

It would be awesome if you could add an option that we can use * to allow all A records of a domain. Like *.MyServer.com would allow the use of play.myserver.com, mc.myserver.com, basically anything :P. Also it would be nice to not block play.myserver.com/forums/, by for instance adding *.myserver.com/*.

I hope you can take this into account, since my members can not share any forum posts and such ;(

Sincerely,

Darthmineboy

**Comment by KasperFranz** [comment]
It is now implemented.

It is only possible to have a start in the beginning of a link or in the end.

Eg:

*.google.com
google.com/*
or *.gooogle.*
