### ISSUE TITLE
Important ! Errors and features

### ISSUE THREAD

**Issue by to175** [antiAD/AntiAd#52]
HI,
=> I have only : log, whitelist and config in the folder.
http://pastebin.com/p3GjDbwq
I thought it could block swearing :confused: swearing is kind of "bad ad" for the server ^^'
- I don't want players who CAPS be warned :disappointed: 
 It doesn't block : EEE EEE EEE or ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !  :disappointed: 
- I set to fr, this is still in english :disappointed: 
- AntiSpam is ver BAD, too slow :
- I need warn+1 when someone say 5 things in 3 seconds :smiley: 
- I need block players to send an other time the  Same thing in chat :smiley: 

"#The Amount of time they are banned for" I don't understand :stuck_out_tongue: 

Thanks :smile:

**Comment by XxCoolGamesxX** [comment]
No news of the User. We go to close the issue. It you have the info please add on is issue and open it.

**Comment by to175** [comment]
Thanks sorry I use reggae now. much better.
