### ISSUE TITLE
Advertising Detection

### ISSUE THREAD

**Issue by UNST3RBLICH** [antiAD/AntiAd#53]
Hello,

[ISSUE]: I have noticed that the Advertising seems to be flagging things which do not contain urls or anything similar to such. Example from the Log:

Feb 13,2015 19:36 Â§2CrystalGreen3Â§r has advertised: thank you...they are after me!, in chat.

Could you please advise if something needs to be changed to correct this, or if it is otherwise a general bug? I do no wish players to be warned or kicked for normal chat lines, and to have their chat suppressed if they are not advertising.

[QUESTION]: If I set something to the whitelist, such as my server website, does this include all pages for the full domain, or just the specific page whitelisted?

Thank you, am enjoying the functionality of this plugin.

- UNST3RBLICH

**Comment by KasperFranz** [comment]
The issues about website is something we are looking into, it's a bit more complex than so, but it is something we are aware of and trying to fix it.

The whitelist is currently very bad atm (i have to say it before you did it ;)) it requires it to be the exact website, we are looking into making this better.

**Comment by UNST3RBLICH** [comment]
Sounds good. Will stay tuned.

**Comment by KasperFranz** [comment]
Sorry to first get back to this problem now, It is a very hard thing to check for 

Currently i have tried different approaches to see if we can look this up another way, so far without any luck.

because of the new TLDs it's very hard to see if it is a link or not, I'm still trying to see if I can do something to this.

**Comment by KasperFranz** [comment]
This should be fixed with the propeisral in #64
