### ISSUE TITLE
chat format error?

### ISSUE THREAD

**Issue by madtomic** [antiAD/AntiAd#54]
&6 Error while trying to execute command!

Just print this in game when user sent an ad.

No error on console.

**Comment by KasperFranz** [comment]
please share your config

**Comment by madtomic** [comment]
Default config

**Comment by madtomic** [comment]
http://s15.postimg.org/92lsg670b/kickerror.png

It seems like the error comes from command. trying to kick after three tries.

**Comment by madtomic** [comment]
http://s15.postimg.org/92lsg670b/kickerror.png

kick error I believe. spigot 1.8

**Comment by XxCoolGamesxX** [comment]
Can you give us the config.yml plz.

**Comment by madtomic** [comment]
http://pastebin.com/GYuvgBKu
