### ISSUE TITLE
Banning Error

### ISSUE THREAD

**Issue by Schneiderism** [antiAD/AntiAd#55]
When a player is temp-banned from the server for advertising, it kicks them and says, "DO NOT ADVERTISE! 300". I have my tempban time set to 5 minutes, or 300 seconds, so I'm guessing that's where it comes from. Ideas on how to fix it?

![capture](https://cloud.githubusercontent.com/assets/11036216/6220021/af25c4b2-b5e5-11e4-8511-a9b41b05d075.PNG)

**Comment by KasperFranz** [comment]
Please share your config.

**Comment by Schneiderism** [comment]
#Standard Languge you wat to use (see http://dev.bukkit.org/server-mods/antiad/ for valid values here)
Language: en
#Command sent to console when someone advertises
Command-Ad: tempban <player> <reasonad> <time>
#Command sent to console when someone spams
Command-Spam: kick <player> <reasonspam>
#The Amount of time they are banned for
Time: 300
#The message players are given if not banned.
Spam_Message: DO NOT SPAM!
#The message players are given if not banned.
Ad_Message: DO NOT ADVERTISE!
#Broadcasts a notification that someone has been punished for advertising
Notification-Message: false
#Says Server is running AntiAd
JoinMsg-On: false
#Check if there are spam
Spam-Detection: false
#Says whether it will detect url's or not
URL-Detection: true
#check if there are any URLS ex. google.com
IP-Detection: true
#Check if all is Caps
Caps-Detection: true
#Checho for long spam 
Spam-Number-Letters-check: true
#Number of characters without a space that become spam
Spam-Number-Letters: 20
#Number of Capital Letters that become spam per word Eg More than 3 Letters Per Word Become Spam
Spam-Procent-Capital-Words: 80
#What commands the plugin listens to (private, me and so on.)
Detected-Commands:
- /msg
- /me
- /t
- /message
- /tell
#Warns admins when a player is spamming
SpamWarnAdmins: true
#Warns a admin when a player is advertising
AdWarnAdmins: true
#Number of times a player can spam/advertise before a action is taken we recommend it's set on 3.)
warnings: 3
