### ISSUE TITLE
emojis on whitelist

### ISSUE THREAD

**Issue by Posse1** [antiAD/AntiAd#56]
Will emojis work on whitelist? if i whitlist something like: =D will it whitelist just that emoji or will it whitelist any sentence with a D and = in it?

if it wont work on the whitelist, is there a way to allow emojies in chat?

**Comment by KasperFranz** [comment]
Emojies is as far as i know not supported by the Minecraft chat.

If smileys in general is blacklisted that is a mistake and i will look into that.

**Comment by Posse1** [comment]
i meant smilies when I said emojies, so things like ":)" ":D" "O_O" etc

**Comment by KasperFranz** [comment]
are they currently being marked as spawn?

**Comment by Posse1** [comment]
Yea they are.

**Comment by Posse1** [comment]
sorry forgot to mention. I do have the anti-caps enabled.

**Comment by Posse1** [comment]
i am going to mark it as solved. i do not think there was any issue. people are not getting warned for spam anymore for sending emojies
