### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by KasperFranz** [antiAD/AntiAd#59]
As of Version 2.3 There are added 2 new strings to the translations

I added them as english strings in the translations, I translated the danish one

Tagged the users there have made translations so far for AntiAd: 
- [x] @kasperfranz - Danish
- [ ] @Mayomi  - Simplified Chinese
- [ ] @AlexMl  - German
- [ ] @XxCoolGamesxX  - Spanish
- [ ] @XxCoolGamesxX  - French
- [ ] @XxCoolGamesxX  - Polish
- [ ] @MySt1k  - Russian
- [ ] @metalun4  - Turkish

Can i get you to update your translations with the 2 new strings :)?

**Comment by XxCoolGamesxX** [comment]
Is done the "Spanish, French, Polish" translations.

**Comment by Mayomi** [comment]
ofc

**Comment by KasperFranz** [comment]
Thank you both :)

**Comment by KasperFranz** [comment]
I'm gonna release tomorrow (in ~27 hours) so if thee translations could be done there it would be quite awesome :)

**Comment by AlexMl** [comment]
I will update my translation too.

**Comment by KasperFranz** [comment]
Perfect, that is perfect @AlexMl.

I updated the initial message which now contains a tasklist :)

**Comment by metalun4** [comment]
I translated new strings to Turkish language and It's ready for the release.

**Comment by KasperFranz** [comment]
@metalun4 can you make a PR  with it :)?

**Comment by metalun4** [comment]
PR?

**Comment by KasperFranz** [comment]
Pull request  :)

**Comment by Mayomi** [comment]
done~!

**Comment by KasperFranz** [comment]
Thank you @mayomi

**Comment by metalun4** [comment]
done with pull request now :)

**Comment by XxCoolGamesxX** [comment]
Thank you @metalun4

**Comment by KasperFranz** [comment]
@MySt1k  Do you have any eta on the Russian translation :)?

**Comment by KasperFranz** [comment]
I added a new string related to the upcoming feature with a message if there is a new build ready at dbo #63
