### ISSUE TITLE
Debug left enabled on latest release

### ISSUE THREAD

**Issue by Yive** [antiAD/AntiAd#65]
![debug](https://i.tcpr.ca/AslQxCG)

**Information:**
AntiAd Version: 2.3.0
Server Version: CraftBukkit version git-PaperSpigot-"a861cc6" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by KasperFranz** [comment]
damn, hope that is only here on github and not everywhere i forgot that

**Comment by KasperFranz** [comment]
releasing a 2.3.1 now with that removed ^^.

I should really not have my debug that way

**Comment by KasperFranz** [comment]
2.3.1 is now released.
Sorry about that :)
