### ISSUE TITLE
[BUG] Warns admins disable

### ISSUE THREAD

**Issue by niqoar** [antiAD/AntiAd#66]
**SpamWarnAdmins** set **false** **in config** and notifies to admins 	equally

Config: http://pastebin.com/ik5Tyy4S
Image: http://i.imgur.com/0ZRV2LM.png

**Comment by KasperFranz** [comment]
Can you try the 2.3.1-dev build :)?

https://github.com/antiAD/AntiAd/releases/tag/2.3.1-dev

**Comment by KasperFranz** [comment]
This is fixed in the latest build
