### ISSUE TITLE
BanManager Compatibility

### ISSUE THREAD

**Issue by GershonR** [antiAD/AntiAd#71]
Config: http://pastebin.com/daczN3p5
Log: http://pastebin.com/tw8sLMMc
Picture:
http://i.imgur.com/WSeAMtl.png

I tried running the command it runs in the config by using:
/tempban player test 1 but got "Your time length is invalid."

**Comment by KasperFranz** [comment]
try to change 

`Command-Ad: tempban <player> <reasonad> <time>` to `Command-Ad: tempban <player> <reasonad> 30m` to ban them for 30 min

**Comment by KasperFranz** [comment]
I'm gonna remove the time paramater  as it is useless and makes more confusion that what it adds

**Comment by KasperFranz** [comment]
I'm marking this as solved, if it isn't please reopen it :)
