### ISSUE TITLE
Breaks with large numbers

### ISSUE THREAD

**Issue by GershonR** [antiAD/AntiAd#72]
http://i.imgur.com/rDtuyRy.png

Also had a user join with a name with lots of numbers and anytime someone tried to invite him to a town/mention him it would count as advertising

**Comment by KasperFranz** [comment]
which version are you using? 
can you also put your config on either gist or pastebin :)?

**Comment by GershonR** [comment]
AntiAD 2.3.2
http://pastebin.com/uPmdFcAX

**Comment by KasperFranz** [comment]
I have to look into this, I'm not sure which filter there is catching that, because as far as I can see it isn't catched by either Ip filter or web filter so might be a problem with the capital checker.

I hope i can get it tested tomorrow evening and make a new build for it at that point :)

**Comment by GershonR** [comment]
Ok thank you for the quick response!

**Comment by KasperFranz** [comment]
The message is: 

> I had 22032032425356 $ :p

**Comment by KasperFranz** [comment]
This is fixed in the that commit.

might end up making a new release later today / this week

**Comment by KasperFranz** [comment]
It is released now on dev.bukkit.org just waiting on approval

**Comment by GershonR** [comment]
Thanks so much! :)
