### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by zMaily** [antiAD/AntiAd#78]
Mesmo SpamWarnAdmins estando em falso, continua avisando administradores. 
Mesmo AdWarnAdmins estando em falso, continua avisando administradores.
Mesmo Caps-Detection entando em falso, continua detectando Caps-Lock.

**Comment by KasperFranz** [comment]
Can you try to explain it in english?

**Comment by zMaily** [comment]
Even SpamWarnAdmins being false, it continues to warn administrators.
Even if AdWarnAdmins is false, it continues to warn administrators.
Even Caps-Detection false, continues to detect Caps-Lock.

**Comment by zMaily** [comment]
Even SpamWarnAdmins being false, it continues to warn administrators.
Even if AdWarnAdmins is false, it continues to warn administrators.
Even Caps-Detection false, continues to detect Caps-Lock.

**Comment by zMaily** [comment]
If you can correct it, I'm grateful.

**Comment by KasperFranz** [comment]
Even SpamWarnAdmins being false, it continues to warn administrators.
I can't recreate this in my small test, can you share your config - either here or as i private message on discord

Even if AdWarnAdmins is false, it continues to warn administrators.
Even Caps-Detection false, continues to detect Caps-Lock.

**Comment by KasperFranz** [comment]
I am going to close this issue, if this is still a problem please respond to it.
