### ISSUE TITLE
Bug on load

### ISSUE THREAD

**Issue by zBoringDrop** [antiAD/AntiAd#79]
Hi, can you fix this?
My server version: 1.12

![image](https://user-images.githubusercontent.com/30697271/36636445-eb784cf2-19c7-11e8-9924-25ecb1ae51d1.png)

**Comment by KasperFranz** [comment]
use the latest version

**Comment by zBoringDrop** [comment]
Can you link me? 
Another think, how i can send you a pm? 
Have you telegram, a discord server or other? (Not bukkit pm)

**Comment by KasperFranz** [comment]
I got a discord server -  https://discord.gg/MD6qGAd.

The latest download on both here and on spigot and bukkit should work, if not where did you download this from?

**Comment by zBoringDrop** [comment]
No, i have your last version

**Comment by KasperFranz** [comment]
as asked earlier
>Where did you download this from?

**Comment by zBoringDrop** [comment]
Bukkit

**Comment by KasperFranz** [comment]
and this work? 

https://github.com/antiAD/AntiAd/releases

**Comment by zBoringDrop** [comment]
Same error .-.

**Comment by KasperFranz** [comment]
I have a note to make a build this weekend and release it on the different platforms - I might put more into it :)

**Comment by zBoringDrop** [comment]
Ok, maybe you can resume your work on spigot

**Comment by KasperFranz** [comment]
I don't have plans on doing spigot and Bukkit, i am only using sponge

**Comment by KasperFranz** [comment]
This is already tracked by #**

**Comment by zBoringDrop** [comment]
Ehm.. your spigot download doesn't work xD

It says: page not found

**Comment by KasperFranz** [comment]
use ticket #77
