### ISSUE TITLE
Can't load plugin

### ISSUE THREAD

**Issue by DevelopmentHigh** [antiAD/AntiAd#84]
![versionmyb](https://user-images.githubusercontent.com/61356848/78985567-62d19780-7b29-11ea-8f34-4bc14a73215b.png)

**Comment by KasperFranz** [comment]
Where did you download it from?

**Comment by DevelopmentHigh** [comment]
https://dev.bukkit.org/projects/antiad

**Comment by KasperFranz** [comment]
Please download it from here for now and I will get thst file updated On 11 Apr 2020 22:02, DevelopmentHigh <notifications@github.com> wrote:
https://dev.bukkit.org/projects/antiad
